name: prueba_tecnica
description: "Prueba TÃ©cnica Flutter - GetX + Hive + API"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management & Dependency Injection
  get: ^4.6.5
  
  # Firebase
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network
  http: ^1.1.0
  
  # Utils
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  
  # UI Helpers
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.4.7
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env